name       : alsa-firmware
version    : 1.2.1
release    : 4
source     :
    - ftp://ftp.alsa-project.org/pub/firmware/alsa-firmware-1.2.1.tar.bz2 : aea27c571dbe02ede298cf9f637d8dfdb758e032e372c8d7e96ccb2b15fa08ab
homepage   : http://www.alsa-project.org
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : ALSA Firmware for certain sound cards
description: |
    ALSA Firmware for certain sound cards
strip      : no
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    # Already provided by linux-firmware package
    cd $installdir/lib/firmware
    rm ctefx.bin ctspeq.bin
    for d in sb16 ess korg yamaha; do
        rm -Rf $d
    done
