name        : alsa-firmware
version     : 1.0.29
release     : 3
source      :
    - ftp://ftp.alsa-project.org/pub/firmware/alsa-firmware-1.0.29.tar.bz2 : 3c5ef17959e58831504d3a25e76d0a428bd9c52ebd330e06b07232ab8af4cc3d
homepage    : http://www.alsa-project.org
license     :
    - GPL-2.0
component   : multimedia.audio
summary     : ALSA Firmware for certain sound cards
description : |
    ALSA Firmware for certain sound cards
strip       : no
setup       : |
    %configure
build       : |
    %make
install     : |
    %make_install
    # Already provided by linux-firmware package
    cd $installdir/lib/firmware
    rm ctefx.bin
    rm ctspeq.bin
    for d in sb16 ess korg yamaha; do
        rm -Rf $d
    done