name       : alsa-firmware
version    : 1.2.4
release    : 5
source     :
    - ftp://ftp.alsa-project.org/pub/firmware/alsa-firmware-1.2.4.tar.bz2 : b67b6d7d08bcfc247ef6ff0ab88a99c188305a3cf57ae2dfd0bcd9a5b36cd5bb
homepage   : http://www.alsa-project.org
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : ALSA Firmware for certain sound cards
description: |
    ALSA Firmware for certain sound cards
strip      : no
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    # Already provided by linux-firmware package
    cd $installdir/lib/firmware
    rm ctefx.bin ctspeq.bin
    for d in sb16 ess korg yamaha; do
        rm -Rf $d
    done
